from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import darkblue
from reportlab.lib.units import inch
from reportlab.lib.styles import ParagraphStyle

import os


class ReportAgent:

    def generate_report(self, kpis, summary):

        os.makedirs("reports", exist_ok=True)

        pdf_path = "reports/Business_Report.pdf"

        doc = SimpleDocTemplate(pdf_path)

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "Title",
            parent=styles["Heading1"],
            alignment=TA_CENTER,
            textColor=darkblue,
            spaceAfter=20,
        )

        story = []

        story.append(
            Paragraph(
                "Agentic AI Business Intelligence Report",
                title_style
            )
        )

        story.append(
            Paragraph("<b>Executive Summary</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(summary, styles["BodyText"])
        )

        story.append(
            Paragraph("<br/><b>Business KPIs</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(f"Total Revenue : ₹{kpis['Total Revenue']:,.0f}", styles["BodyText"])
        )

        story.append(
            Paragraph(f"Total Profit : ₹{kpis['Total Profit']:,.0f}", styles["BodyText"])
        )

        story.append(
            Paragraph(f"Profit Margin : {kpis['Profit Margin %']}%", styles["BodyText"])
        )

        story.append(
            Paragraph(f"Top Product : {kpis['Top Product']}", styles["BodyText"])
        )

        story.append(
            Paragraph(f"Top Region : {kpis['Top Region']}", styles["BodyText"])
        )

        story.append(
            Paragraph("<br/><b>Generated By</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(
                "Agentic AI Business Intelligence Assistant",
                styles["BodyText"]
            )
        )

        doc.build(story)

        return pdf_path